Repository jenkins-x/jenkins-x-builders-base-image, pull requests merged in 2019-09, with the labels that each got.

#24 feat: removing java from the base image installation
  .updatebot.yml
  Dockerfile.common
  Dockerfile.ruby
  Dockerfile.swift
  jenkins-x.yml
  update-bot.sh
Labels: approved, size/M

#25 fix: corrected step name
  jenkins-x.yml
Labels: approved, size/XS

#26 fix: downstream repo build
  update-bot.sh
Labels: approved, size/XS

#27 feat: added pre-commit and detect-secrets
  Dockerfile.common
Labels: approved, lgtm, size/XS

#28 fix: an attempt to slim down the image size
  Dockerfile.common
Labels: approved, lgtm, size/M

#29 chore: Clean up the git source
  Dockerfile.common
Labels: approved, lgtm, size/XS
