Repository jenkins-x/jenkins-x-builders-base-image, pull requests merged in 2019-07, with the labels that each got.

#15 fix: removed older version of git
  Dockerfile
Labels: approved, size/XS

#17 feat: Install yamale for yaml validation
  Dockerfile
  Dockerfile.ruby
  Dockerfile.swift
Labels: approved, lgtm, size/XS

#18 chore: Add builder-*-baseimages for machine learning + ml gpu
  Dockerfile.common
  Dockerfile.machinelearning
  Dockerfile.machinelearninggpu
  jenkins-x.yml
  prep-centos-dockerfiles.sh
Labels: approved, lgtm, size/L

#19 chore: Set memory limits for containers
  jenkins-x.yml
Labels: approved, lgtm, size/S

#21 chore: added precommit configuration
  .pre-commit-config.yaml
  .secrets.baseline
Labels: approved, size/M
